#!/usr/bin/env bash
# Function to display information about a subdomain
display_subdomain_info() {
  local domain="$1"
  local subdomain="$2"
  local record_type=$(dig +short "$subdomain.$domain" | awk '{print $4}')
  local destination=$(dig +short "$subdomain.$domain" | awk '{print $5}')

  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script logic
domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
  # Display information for default subdomains
  display_subdomain_info "$domain" "www"
  display_subdomain_info "$domain" "lb-01"
  display_subdomain_info "$domain" "web-01"
  display_subdomain_info "$domain" "web-02"
else
  # Display information for specified subdomain
  display_subdomain_info "$domain" "$subdomain"
fi
