#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure custom HTTP header
sudo sed -i '/http {/a \    server_tokens off;\n\n    location / {\n        add_header X-Served-By $hostname;\n    }' /etc/nginx/nginx.conf

# Restart Nginx
sudo systemctl restart nginx
