#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.

hour=0
minute=1

while [[ $hour -lt 12 && $minute -lt 60 ]]
do
    echo "Hour: $hour"

    while [[ $minute -lt 60 ]]
    do
        echo $minute
        minute=$((minute+1))

        if [[ $hour -eq 12 && $minute -eq 60 ]]
        then
            break
        fi

        if [[ $(($hour*60 + $minute)) -eq 780 ]]
        then
            break 2
        fi
    done

    hour=$((hour+1))
    minute=1
done
